version: '3.9'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jabpoint
    ports:
      - "3000:80" # Map port 8080 on host to port 80 in the container
    volumes:
      - .:/var/www/html # Mount the current directory to the container's web root
    environment:
      - APP_ENV=${APP_ENV} # Pass the environment variable from .env
